### ISSUE TITLE
Pesquisa de letra maiúscula e minúscula

### ISSUE THREAD

**Issue by lucasalmeida00** [LaravelLegends/eloquent-filter#1]
Ao utilizar reparei que a biblioteca não pesquisa tanto letra maiúscula quanto minúscula, a pesquisa tem que estar totalmente igual ao que está na base de dados.
Então no contains encontrei a seguinte solução:

```php
class Contains implements Searchable
{
    public function __invoke($query, $field, $value)
    {
        //$query->where($field, 'LIKE', "%{$value}%");
        $query->whereRaw("LOWER($field) like ?", '%' . strtolower($value) . '%');
    }
}
```

**Comment by brcontainer** [comment]
@lucasalmeida00 obrigado por sugerir, só tenha em mente que `strtolower` não vai funcionar com acentos, e também existe a questão do charset escolhido para o banco, o melhor mesmo será implementar isso tudo baseado na na estrutura da tabela, leve em consideração que se você usa `_ci` vai funcionar com `LIKE` sem precisar converter nada, enquanto os charset que não tem `_ci`, essa questão deve ser sempre abordada na modelagem ao invés da query ou do ORM.

Porque é justamente para isso que existe charset com `_ci` e sem, recomendo que leia: https://dev.mysql.com/doc/refman/8.0/en/charset-collation-names.html

Mas vou deixar pro @wallacemaxters decidir

**Comment by brcontainer** [comment]
@lucasalmeida00 Bom, só pra constar, com `_ci` e com o charset da página tudo nos conformes, trabalhando tudo alinhado você vai poder pesquisar comparar minúsculas com maiúsculas e compara até a com á, à, etc, sem diferenciar (verifique o collection que está usando se não tem algum detalhe adicional).

Se tiver alguma duvida sobre isso, fora o link, pode experimentar perguntar no https://pt.stackoverflow.com/questions/ask (frequentamos lá também).

**Comment by wallacemaxters** [comment]
Existe um método chamado `setRule` em  `Filter`. Com ele você é capaz de substituir ou adicionar um novo comportamento ao `Filter`.

Exemplo

```php
$filter = (new Filter)->setRule('contains', function ($query, $field, $value) {
     $query->whereRaw("LOWER($field) like ?", '%' . strtolower($value) . '%');
});

$filter->apply($query = User::query(), $request);

return $query->get();
```

Estava trabalhando para reduzir o número de linhas dessa implementação, já que eu havia colocado o service provider de Filter para atuar com `bind` ao invés de `singleton`.

## Atualização

Na versão 2.0.2, é possível sobrescrever ou adicionar novas regras ao Filter. 

Basta lembrar de incluir o `LaravelLegends\EloquentFilter\FilterServiceProvider::class`, no `config/app.php` se estiver usando laravel, e `bootstrap/app.php` se estiver usando Lumen. Em seguida, você pode modificar a implementação no seu `AppServiceProvider`.

Assim:

```php
use LaravelLegends\EloquentFilter\Facades\Filter;

public function boot()
{
      Filter::setRule('contains', function ($query, $field, $value)  {
           $query->whereRaw("LOWER($field) like ?", '%' . strtolower($value) . '%');
      });
}
```

```php
class User extends Model
{
     use HasFilter;
}

```
```php
public function index()
{
       dd(User::filter()->toSql());
}
```
